name: Test lint
on: [pull_request, push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint with config
        uses: ./
        with:
          file_or_dir: ./
